changelog:
  categories:
    - title: "🚀 Features"
      labels: ["enhancement"]
    - title: "🐛 Bug Fixes"
      labels: ["bug"]
    - title: "⚡ Performance"
      labels: ["performance"]
    - title: "📖 Documentation"
      labels: ["documentation"]
  exclude:
    labels: ["skip-changelog"]
